#!/usr/bin/env python3
# Regenerate src/lut_tables.c from the trained soft-gain tables in
# test/. The plugin embeds these as the default separation mode; the
# lut parameter overrides them.
#
# usage: gen_lut_tables.py [repo_root]
import os
import sys

import numpy as np

root = sys.argv[1] if len(sys.argv) > 1 else \
    os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

TABLES = [
    ('comp_lut_builtin_pal_2d', 'test/lut_pal_2d.txt', 80 * 16),
    ('comp_lut_builtin_pal_3d', 'test/lut_pal_3d.txt', 768 * 16),
    ('comp_lut_builtin_ntsc', 'test/lut_ntsc.txt', 768 * 16),
]

c = ['/*',
     ' * Trained soft-gain separation tables (see lut_tables.h).',
     ' * Generated by test/gen_lut_tables.py from the test/lut_*.txt',
     ' * tables; regenerate rather than editing.',
     ' */',
     '',
     '#include "lut_tables.h"',
     '']
h = ['#ifndef COMP_LUT_TABLES_H',
     '#define COMP_LUT_TABLES_H',
     '',
     '/* Trained per-bin soft-gain tables (Wiener gains over the pair-',
     ' * symmetry ratio, 16 knots per bin; the format comp_decode_set_lut',
     ' * takes). Trained by test/calibrate_thresholds.py; regenerated by',
     ' * test/gen_lut_tables.py. */',
     '']
for name, path, n in TABLES:
    v = np.loadtxt(os.path.join(root, path))
    assert v.size == n, (path, v.size, n)
    h.append(f'extern const double {name}[{n}];')
    c.append(f'const double {name}[{n}] = {{')
    for i in range(0, n, 8):
        row = ', '.join(f'{x:.4f}' for x in v[i:i + 8])
        c.append(f'    {row},')
    c.append('};')
    c.append('')
h += ['', '#endif', '']

open(os.path.join(root, 'src/lut_tables.c'), 'w').write('\n'.join(c))
open(os.path.join(root, 'src/lut_tables.h'), 'w').write('\n'.join(h))
print('wrote src/lut_tables.c and src/lut_tables.h')
