#!/usr/bin/env python3
"""Regenerate the Rust build input from the calibrated LUT text files."""

from pathlib import Path
import sys

import numpy as np


ROOT = Path(sys.argv[1]).resolve() if len(sys.argv) > 1 else Path(__file__).resolve().parents[1]
TABLES = [
    ("comp_lut_builtin_pal_2d", ROOT / "data/luts/pal-2d.txt", 80 * 16),
    ("comp_lut_builtin_pal_3d", ROOT / "data/luts/pal-3d.txt", 384 * 16),
    ("comp_lut_builtin_ntsc", ROOT / "data/luts/ntsc-3d.txt", 768 * 16),
]

lines = [
    "/*",
    " * Trained soft-gain separation tables.",
    " * Generated by tools/gen_lut_tables.py from data/luts/*.txt.",
    " * This file is parsed by build.rs and is not compiled as C.",
    " */",
    "",
]
for name, path, expected_length in TABLES:
    values = np.loadtxt(path)
    assert values.size == expected_length, (path, values.size, expected_length)
    lines.append(f"const double {name}[{expected_length}] = {{")
    for offset in range(0, expected_length, 8):
        row = ", ".join(f"{value:.4f}" for value in values[offset : offset + 8])
        lines.append(f"    {row},")
    lines.extend(["};", ""])

output = ROOT / "data/lut_tables.inc"
output.write_text("\n".join(lines), encoding="utf-8")
print(f"wrote {output}")
