//! Composite decoding with spatial and temporal spectral separation.
//!
//! The public decoder keeps timing dependencies explicit.

use std::sync::Arc;

#[path = "lut.rs"]
mod lut;
#[path = "transform.rs"]
mod transform;

use self::transform::{
    LUT_KNOTS, NTSC_3D_BINS, PAL_2D_BINS, PAL_3D_BINS, SeparationRule, SeparationSettings,
    TemporalStandard, Transform2d, Transform3d, TransformScratch,
};
use crate::encode::{level_parameters, round_div};
use crate::model::{FrameIndex, GraySink, GraySource, Plane, PlaneMut, Setup, Standard, YuvSink};
use crate::subcarrier::{line_phase, sine_table};

const MAX_WIDTH: usize = 928;
const COLOR_TAPS: [i32; 17] = [
    73, 317, 200, -682, -1_597, -503, 3_726, 9_094, 11_579, 9_094, 3_726, -503, -1_597, -682, 200,
    317, 73,
];

/// Chroma-separation strategy.
#[derive(Clone, Copy, Debug, Default, Eq, PartialEq)]
pub enum DecodeMode {
    /// A one-line notch decoder. Useful as a degradation reference.
    Notch,
    /// PAL uses a two-dimensional spectral separator; NTSC uses an adaptive
    /// same-field line comb.
    #[default]
    SpatialComb,
    /// A three-dimensional spectral separator with four frame neighbours on
    /// each side of the output frame.
    TemporalTransform,
}

impl DecodeMode {
    /// Converts the public `dimensions` argument into a decoder strategy.
    pub fn from_dimensions(value: i64) -> Result<Self, DecodeConfigError> {
        match value {
            1 => Ok(Self::Notch),
            2 => Ok(Self::SpatialComb),
            3 => Ok(Self::TemporalTransform),
            _ => Err(DecodeConfigError::UnsupportedDimensions(value)),
        }
    }
}

/// The NTSC policy selected for three-dimensional decoding.
#[derive(Clone, Copy, Debug, Default, Eq, PartialEq)]
pub enum NtscTemporalMode {
    /// Use the adaptive spatial comb result.
    Comb,
    /// Use the temporal spectral result.
    Transform,
    /// Use the comb on still pixels and the temporal transform where motion
    /// makes the comb unreliable.
    #[default]
    Hybrid,
}

/// An optional per-sample diagnostic image generated by a decode.
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub enum MaskKind {
    /// White identifies pixels routed to the temporal transform by NTSC's
    /// hybrid motion router.
    Motion,
    /// White identifies weak spectral-separation confidence.
    Confidence,
}

/// Decoder settings that do not change while a clip is processed.
#[derive(Clone, Debug)]
pub struct DecoderOptions {
    mode: DecodeMode,
    threshold: f32,
    thresholds: Option<Arc<[f32]>>,
    amplitude_limit: bool,
    evidence: f32,
    ntsc_temporal: NtscTemporalMode,
    lut: Option<Arc<[f32]>>,
    builtin_lut: bool,
}

impl DecoderOptions {
    /// Builds the reference threshold configuration for `mode`.
    #[must_use]
    pub fn new(mode: DecodeMode) -> Self {
        Self {
            mode,
            threshold: 0.4,
            thresholds: None,
            amplitude_limit: false,
            evidence: 0.0,
            ntsc_temporal: NtscTemporalMode::Hybrid,
            lut: None,
            builtin_lut: true,
        }
    }

    /// Changes the pair-symmetry threshold. Construction validates it.
    #[must_use]
    pub fn with_threshold(mut self, threshold: f32) -> Self {
        self.threshold = threshold;
        self.thresholds = None;
        self.builtin_lut = false;
        self
    }

    /// Selects an individual pair-symmetry threshold for every transform bin.
    #[must_use]
    pub fn with_thresholds(mut self, values: Vec<f32>) -> Self {
        self.thresholds = Some(Arc::from(values));
        self.amplitude_limit = false;
        self.lut = None;
        self.builtin_lut = false;
        self
    }

    /// Selects amplitude limiting instead of a hard pair-symmetry threshold.
    #[must_use]
    pub fn with_amplitude_limit(mut self, enabled: bool) -> Self {
        self.amplitude_limit = enabled;
        if enabled {
            self.thresholds = None;
            self.lut = None;
            self.builtin_lut = false;
        }
        self
    }

    /// Adds the PAL low-frequency luma-evidence prior.
    #[must_use]
    pub fn with_evidence(mut self, evidence: f32) -> Self {
        self.evidence = evidence;
        self
    }

    /// Selects a NTSC temporal routing policy.
    #[must_use]
    pub fn with_ntsc_temporal_mode(mut self, mode: NtscTemporalMode) -> Self {
        self.ntsc_temporal = mode;
        self
    }

    /// Installs a 16-knot trained soft-gain table. Its exact size and range
    /// are validated against the selected transform at construction time.
    #[must_use]
    pub fn with_lut(mut self, values: Vec<f32>) -> Self {
        self.lut = Some(Arc::from(values));
        self.thresholds = None;
        self.amplitude_limit = false;
        self.builtin_lut = false;
        self
    }

    /// Restores the calibrated gain table selected by the standard and mode.
    #[must_use]
    pub fn with_builtin_lut(mut self, enabled: bool) -> Self {
        self.builtin_lut = enabled;
        if enabled {
            self.thresholds = None;
            self.amplitude_limit = false;
            self.lut = None;
        }
        self
    }

    /// Returns the requested decoding strategy.
    #[must_use]
    pub const fn mode(&self) -> DecodeMode {
        self.mode
    }
}

/// Metrics generated while decoding one frame.
#[derive(Clone, Copy, Debug, Default, PartialEq)]
pub struct DecodeReport {
    /// Mean spectral-separation confidence, when a transform path ran.
    pub confidence_mean: Option<f64>,
    /// Population standard deviation of separation confidence.
    pub confidence_std_dev: Option<f64>,
    /// Fraction of samples routed to the transform in NTSC hybrid mode.
    pub motion_fraction: Option<f64>,
}

/// Reusable buffer arena for one constant-format composite frame.
///
/// The hot decoder takes this storage from the owning filter instead of
/// allocating an image-sized buffer while a frame request is active.
#[derive(Debug)]
pub struct DecodeScratch {
    width: usize,
    height: usize,
    separated: Vec<f32>,
    chroma: Vec<i32>,
    comb: Vec<i32>,
    confidence: Vec<f32>,
    motion: Vec<u8>,
    mask_row: Vec<u16>,
    has_confidence: bool,
    has_motion: bool,
    transform: TransformScratch,
}

impl DecodeScratch {
    /// Allocates the fixed buffers needed for a constant raster geometry.
    pub fn new(width: usize, height: usize) -> Result<Self, DecodeError> {
        let length = width
            .checked_mul(height)
            .ok_or(DecodeError::ScratchSizeOverflow { width, height })?;
        Ok(Self {
            width,
            height,
            separated: vec![0.0; length],
            chroma: vec![0; length],
            comb: vec![0; length],
            confidence: vec![0.0; length],
            motion: vec![0; length],
            mask_row: vec![0; width],
            has_confidence: false,
            has_motion: false,
            transform: TransformScratch::new(),
        })
    }

    /// Writes one diagnostic image from the most recent decode into `output`.
    pub fn write_mask<D: GraySink>(
        &mut self,
        kind: MaskKind,
        output: &mut D,
    ) -> Result<(), DecodeError> {
        if output.dimensions() != (self.width, self.height) {
            return Err(DecodeError::MaskGeometry {
                expected: (self.width, self.height),
                actual: output.dimensions(),
            });
        }
        match kind {
            MaskKind::Motion if !self.has_motion => return Err(DecodeError::MaskUnavailable(kind)),
            MaskKind::Confidence if !self.has_confidence => {
                return Err(DecodeError::MaskUnavailable(kind));
            }
            _ => {}
        }
        for row in 0..self.height {
            let start = row * self.width;
            match kind {
                MaskKind::Motion => {
                    for (destination, &value) in self
                        .mask_row
                        .iter_mut()
                        .zip(&self.motion[start..start + self.width])
                    {
                        *destination = u16::from(value) * u16::MAX;
                    }
                }
                MaskKind::Confidence => {
                    for (destination, &value) in self
                        .mask_row
                        .iter_mut()
                        .zip(&self.confidence[start..start + self.width])
                    {
                        *destination =
                            ((1.0 - value.clamp(0.0, 1.0)) * f32::from(u16::MAX)).round() as u16;
                    }
                }
            }
            output.write_row(row, &self.mask_row);
        }
        Ok(())
    }

    fn validate_geometry(&self, width: usize, height: usize) -> Result<(), DecodeError> {
        if (width, height) == (self.width, self.height) {
            Ok(())
        } else {
            Err(DecodeError::ScratchGeometry {
                expected: (self.width, self.height),
                actual: (width, height),
            })
        }
    }
}

/// Immutable decoder state and preplanned FFT transforms.
pub struct Decoder {
    standard: Standard,
    mode: DecodeMode,
    ntsc_temporal: NtscTemporalMode,
    sine: Box<[i16]>,
    black: i32,
    luma_num: i32,
    luma_den: i32,
    ku: i32,
    kv: i32,
    comb_range: f32,
    transform_2d: Option<Transform2d>,
    transform_3d: Option<Transform3d>,
}

impl Decoder {
    /// Constructs a decoder using the default configuration for `mode`.
    #[must_use]
    pub fn new(standard: Standard, setup: Setup, mode: DecodeMode) -> Self {
        match Self::with_options(standard, setup, DecoderOptions::new(mode)) {
            Ok(decoder) => decoder,
            Err(_) => unreachable!("the built-in decoder options are valid"),
        }
    }

    /// Validates options and creates immutable FFT plans and signal constants.
    pub fn with_options(
        standard: Standard,
        setup: Setup,
        options: DecoderOptions,
    ) -> Result<Self, DecodeConfigError> {
        let DecoderOptions {
            mode,
            threshold,
            thresholds,
            amplitude_limit,
            evidence,
            ntsc_temporal,
            lut,
            builtin_lut: use_builtin_lut,
        } = options;
        if !(threshold > 0.0 && threshold <= 1.0) {
            return Err(DecodeConfigError::InvalidThreshold(threshold));
        }
        if evidence < 0.0 {
            return Err(DecodeConfigError::InvalidEvidence(evidence));
        }
        let transform = uses_transform(standard, mode, ntsc_temporal);
        if evidence > 0.0 && !(standard == Standard::Pal && transform) {
            return Err(DecodeConfigError::UnsupportedEvidence);
        }
        let expected_lut = lut_length(standard, mode, ntsc_temporal);
        if let Some(values) = thresholds.as_ref() {
            let expected = expected_lut / LUT_KNOTS;
            if expected == 0 {
                return Err(DecodeConfigError::ThresholdsNeedTransform);
            }
            if values.len() != expected {
                return Err(DecodeConfigError::ThresholdLength {
                    expected,
                    actual: values.len(),
                });
            }
            if values.iter().any(|&value| !(value > 0.0 && value <= 1.0)) {
                return Err(DecodeConfigError::InvalidThresholdValue);
            }
        }
        if let Some(values) = lut.as_ref() {
            if expected_lut == 0 {
                return Err(DecodeConfigError::LutNeedsTransform);
            }
            if values.len() != expected_lut {
                return Err(DecodeConfigError::LutLength {
                    expected: expected_lut,
                    actual: values.len(),
                });
            }
            if values.iter().any(|&value| !(0.0..=1.0).contains(&value)) {
                return Err(DecodeConfigError::InvalidLutValue);
            }
        }
        let rule = if let Some(values) = lut {
            SeparationRule::TrainedLut(values)
        } else if amplitude_limit {
            SeparationRule::AmplitudeLimit
        } else if let Some(values) = thresholds {
            SeparationRule::Thresholds(Arc::from(
                values.iter().map(|value| value * value).collect::<Vec<_>>(),
            ))
        } else if use_builtin_lut {
            match builtin_lut(standard, mode, ntsc_temporal) {
                Some(values) => SeparationRule::TrainedLut(values),
                None => SeparationRule::Threshold,
            }
        } else {
            SeparationRule::Threshold
        };
        let settings = SeparationSettings::new(threshold, evidence, rule);
        let transform_2d = if standard == Standard::Pal && mode == DecodeMode::SpatialComb {
            Some(Transform2d::new(settings.clone()))
        } else {
            None
        };
        let transform_3d = if mode == DecodeMode::TemporalTransform && transform {
            let temporal_standard = match standard {
                Standard::Pal => TemporalStandard::Pal,
                Standard::Ntsc => TemporalStandard::Ntsc,
            };
            Some(Transform3d::new(settings, temporal_standard))
        } else {
            None
        };
        let (black, luma_num, luma_den, ku, kv) = level_parameters(standard, setup);
        Ok(Self {
            standard,
            mode,
            ntsc_temporal,
            sine: sine_table(standard.raster().phase_denominator as usize),
            black,
            luma_num,
            luma_den,
            ku,
            kv,
            comb_range: 45.0 * (f32::from(0xc800_u16) - black as f32) / 100.0,
            transform_2d,
            transform_3d,
        })
    }

    /// Returns the selected broadcast standard.
    #[must_use]
    pub const fn standard(&self) -> Standard {
        self.standard
    }

    /// Returns the selected decoding strategy.
    #[must_use]
    pub const fn mode(&self) -> DecodeMode {
        self.mode
    }

    /// Returns how many clamped source frames are required on either side.
    #[must_use]
    pub const fn look(&self) -> usize {
        match self.mode {
            DecodeMode::TemporalTransform => 4,
            DecodeMode::Notch | DecodeMode::SpatialComb => 0,
        }
    }

    /// Decodes one packed composite frame into YUV444P16.
    pub fn decode(
        &self,
        frame: FrameIndex,
        row_offset: usize,
        composite: Plane<'_>,
        y: PlaneMut<'_>,
        u: PlaneMut<'_>,
        v: PlaneMut<'_>,
    ) -> Result<(), DecodeError> {
        struct Sink<'a> {
            y: PlaneMut<'a>,
            u: PlaneMut<'a>,
            v: PlaneMut<'a>,
        }
        impl YuvSink for Sink<'_> {
            fn dimensions(&self) -> (usize, usize) {
                self.y.dimensions()
            }

            fn write_row(&mut self, row: usize, y: &[u16], u: &[u16], v: &[u16]) {
                self.y.row_mut(row).copy_from_slice(y);
                self.u.row_mut(row).copy_from_slice(u);
                self.v.row_mut(row).copy_from_slice(v);
            }
        }
        self.decode_source(frame, row_offset, &composite, &mut Sink { y, u, v })
    }

    /// Decodes a one-frame source. Temporal mode deliberately rejects this
    /// convenience API instead of silently degrading to spatial processing.
    pub fn decode_source<S: GraySource, D: YuvSink>(
        &self,
        frame: FrameIndex,
        row_offset: usize,
        composite: &S,
        output: &mut D,
    ) -> Result<(), DecodeError> {
        if self.look() != 0 {
            return Err(DecodeError::TemporalFramesRequired);
        }
        let (width, height) = composite.dimensions();
        let mut scratch = DecodeScratch::new(width, height)?;
        let frames: [&dyn GraySource; 1] = [composite];
        let frame_indices = [frame];
        self.decode_window_with_scratch(row_offset, &frames, &frame_indices, output, &mut scratch)
            .map(|_| ())
    }

    /// Decodes a one-frame source using caller-owned reusable scratch.
    pub fn decode_source_with_scratch<S: GraySource, D: YuvSink>(
        &self,
        frame: FrameIndex,
        row_offset: usize,
        composite: &S,
        output: &mut D,
        scratch: &mut DecodeScratch,
    ) -> Result<DecodeReport, DecodeError> {
        if self.look() != 0 {
            return Err(DecodeError::TemporalFramesRequired);
        }
        let frames: [&dyn GraySource; 1] = [composite];
        let frame_indices = [frame];
        self.decode_window_with_scratch(row_offset, &frames, &frame_indices, output, scratch)
    }

    /// Decodes the center of a validated one- or nine-frame source window.
    pub fn decode_window_with_scratch<D: YuvSink>(
        &self,
        row_offset: usize,
        frames: &[&dyn GraySource],
        frame_indices: &[FrameIndex],
        output: &mut D,
        scratch: &mut DecodeScratch,
    ) -> Result<DecodeReport, DecodeError> {
        let expected = self.look() * 2 + 1;
        if frames.len() != expected || frame_indices.len() != expected {
            return Err(DecodeError::TemporalWindow {
                expected,
                frames: frames.len(),
                indices: frame_indices.len(),
            });
        }
        let center = self.look();
        let current = frames[center];
        let dimensions = current.dimensions();
        self.validate_geometry(row_offset, dimensions, output, scratch)?;
        for source in frames {
            if source.dimensions() != dimensions {
                return Err(DecodeError::TemporalGeometry {
                    expected: dimensions,
                    actual: source.dimensions(),
                });
            }
        }
        scratch.has_confidence = false;
        scratch.has_motion = false;
        scratch.motion.fill(0);
        match self.mode {
            DecodeMode::Notch => self.separate_notch(current, scratch),
            DecodeMode::SpatialComb => self.separate_spatial_or_transform(current, scratch),
            DecodeMode::TemporalTransform => self.separate_temporal(frames, scratch),
        }
        let report = report(scratch);
        let width = dimensions.0;
        for row in 0..dimensions.1 {
            let start = row * width;
            let mut y = [0_u16; MAX_WIDTH];
            let mut u = [0_u16; MAX_WIDTH];
            let mut v = [0_u16; MAX_WIDTH];
            self.demodulate_row(
                frame_indices[center],
                row + row_offset,
                current.row(row),
                &scratch.chroma[start..start + width],
                &mut y[..width],
                &mut u[..width],
                &mut v[..width],
            );
            output.write_row(row, &y[..width], &u[..width], &v[..width]);
        }
        Ok(report)
    }

    fn validate_geometry<D: YuvSink>(
        &self,
        row_offset: usize,
        dimensions: (usize, usize),
        output: &D,
        scratch: &DecodeScratch,
    ) -> Result<(), DecodeError> {
        let expected_width = self.standard.raster().width;
        if dimensions.0 != expected_width || output.dimensions() != dimensions {
            return Err(DecodeError::PlaneGeometry {
                expected_width,
                composite: dimensions,
                y: output.dimensions(),
                u: output.dimensions(),
                v: output.dimensions(),
            });
        }
        if row_offset + dimensions.1 > self.standard.raster().full_height {
            return Err(DecodeError::RasterPlacement {
                row_offset,
                rows: dimensions.1,
                raster_height: self.standard.raster().full_height,
            });
        }
        scratch.validate_geometry(dimensions.0, dimensions.1)
    }

    fn separate_notch(&self, source: &dyn GraySource, scratch: &mut DecodeScratch) {
        let (width, height) = source.dimensions();
        for row in 0..height {
            let start = row * width;
            bandpass(
                source.row(row),
                &mut scratch.separated[start..start + width],
            );
        }
        quantize_chroma(&scratch.separated, &mut scratch.chroma);
    }

    fn separate_spatial_or_transform(&self, source: &dyn GraySource, scratch: &mut DecodeScratch) {
        if let Some(transform) = self.transform_2d.as_ref() {
            transform.separate(
                source,
                &mut scratch.separated,
                Some(&mut scratch.confidence),
                &mut scratch.transform,
            );
            scratch.has_confidence = true;
            quantize_chroma(&scratch.separated, &mut scratch.chroma);
        } else {
            self.separate_spatial(source, &mut scratch.chroma);
        }
    }

    fn separate_temporal(&self, frames: &[&dyn GraySource], scratch: &mut DecodeScratch) {
        match self.ntsc_temporal {
            NtscTemporalMode::Comb => self.separate_spatial(frames[4], &mut scratch.chroma),
            NtscTemporalMode::Transform | NtscTemporalMode::Hybrid => {
                let transform = match self.transform_3d.as_ref() {
                    Some(transform) => transform,
                    None => unreachable!("transform mode always creates a spectral transform"),
                };
                transform.separate_center(
                    frames,
                    &mut scratch.separated,
                    Some(&mut scratch.confidence),
                    &mut scratch.transform,
                );
                scratch.has_confidence = true;
                quantize_chroma(&scratch.separated, &mut scratch.chroma);
                if self.standard == Standard::Ntsc && self.ntsc_temporal == NtscTemporalMode::Hybrid
                {
                    self.separate_spatial(frames[4], &mut scratch.comb);
                    self.apply_hybrid_motion(frames[3], frames[4], frames[5], scratch);
                }
            }
        }
    }

    fn separate_spatial(&self, source: &dyn GraySource, output: &mut [i32]) {
        let (width, height) = source.dimensions();
        let mut current = [0_f32; MAX_WIDTH];
        let mut previous = [0_f32; MAX_WIDTH];
        let mut next = [0_f32; MAX_WIDTH];
        for row in 0..height {
            bandpass(source.row(row), &mut current[..width]);
            if let Some(above) = row.checked_sub(2) {
                bandpass(source.row(above), &mut previous[..width]);
            } else {
                previous[..width].fill(0.0);
            }
            if row + 2 < height {
                bandpass(source.row(row + 2), &mut next[..width]);
            } else {
                next[..width].fill(0.0);
            }
            spatial_comb(
                &current[..width],
                &previous[..width],
                &next[..width],
                self.comb_range,
                &mut output[row * width..(row + 1) * width],
            );
        }
    }

    fn apply_hybrid_motion(
        &self,
        previous: &dyn GraySource,
        current: &dyn GraySource,
        next: &dyn GraySource,
        scratch: &mut DecodeScratch,
    ) {
        let (width, height) = current.dimensions();
        for row in 0..height {
            let before = previous.row(row);
            let now = current.row(row);
            let after = next.row(row);
            let start = row * width;
            for x in 0..width {
                let left = x.saturating_sub(2);
                let right = (x + 2).min(width - 1);
                let mut difference = 0_i32;
                for sample in left..=right {
                    difference =
                        difference.max((i32::from(now[sample]) - i32::from(before[sample])).abs());
                    difference =
                        difference.max((i32::from(now[sample]) - i32::from(after[sample])).abs());
                }
                let use_transform = difference as f32 >= self.comb_range;
                scratch.motion[start + x] = u8::from(use_transform);
                if !use_transform {
                    scratch.chroma[start + x] = scratch.comb[start + x];
                }
            }
        }
        scratch.has_motion = true;
    }

    #[allow(clippy::too_many_arguments)]
    fn demodulate_row(
        &self,
        frame: FrameIndex,
        raster_row: usize,
        composite: &[u16],
        chroma: &[i32],
        y: &mut [u16],
        u: &mut [u16],
        v: &mut [u16],
    ) {
        let width = composite.len();
        let mut product_sine = [0_i32; MAX_WIDTH];
        let mut product_cosine = [0_i32; MAX_WIDTH];
        for x in 0..width {
            product_sine[x] = match x & 3 {
                1 => chroma[x],
                3 => -chroma[x],
                _ => 0,
            };
            product_cosine[x] = match x & 3 {
                0 => chroma[x],
                2 => -chroma[x],
                _ => 0,
            };
        }
        let mut p = [0_i32; MAX_WIDTH];
        let mut q = [0_i32; MAX_WIDTH];
        fir_row(&product_sine[..width], &COLOR_TAPS, &mut p[..width]);
        fir_row(&product_cosine[..width], &COLOR_TAPS, &mut q[..width]);
        let carrier = line_phase(self.standard, frame, raster_row);
        let denominator = self.standard.raster().phase_denominator as usize;
        let sin = i32::from(self.sine[carrier.phase]);
        let cos = i32::from(self.sine[(carrier.phase + denominator / 4) % denominator]);
        let sine4 = [sin, cos, -sin, -cos];
        let cosine4 = [
            carrier.v_switch * cos,
            -carrier.v_switch * sin,
            -carrier.v_switch * cos,
            carrier.v_switch * sin,
        ];
        for x in 0..width {
            let demod_u =
                -((i64::from(p[x]) * i64::from(-cos) + i64::from(q[x]) * i64::from(-sin) + 8_192)
                    >> 14) as i32;
            let demod_v = carrier.v_switch
                * (-((i64::from(q[x]) * i64::from(-cos) - i64::from(p[x]) * i64::from(-sin)
                    + 8_192)
                    >> 14) as i32);
            let resynthesized = (demod_u * sine4[x & 3] + demod_v * cosine4[x & 3] + 16_384) >> 15;
            let luma_level = i32::from(composite[x])
                - if self.mode == DecodeMode::Notch {
                    chroma[x]
                } else {
                    resynthesized
                };
            y[x] = clamp_u16(
                4_096
                    + round_div(
                        i64::from(luma_level - self.black) * i64::from(self.luma_num),
                        self.luma_den,
                    ),
            );
            u[x] = clamp_u16(32_768 + round_div(i64::from(demod_u) * 32_768, self.ku));
            v[x] = clamp_u16(32_768 + round_div(i64::from(demod_v) * 32_768, self.kv));
        }
    }
}

fn builtin_lut(
    standard: Standard,
    mode: DecodeMode,
    ntsc_mode: NtscTemporalMode,
) -> Option<Arc<[f32]>> {
    match (standard, mode, ntsc_mode) {
        (Standard::Pal, DecodeMode::SpatialComb, _) => Some(lut::pal_2d()),
        (Standard::Pal, DecodeMode::TemporalTransform, _) => Some(lut::pal_3d()),
        (
            Standard::Ntsc,
            DecodeMode::TemporalTransform,
            NtscTemporalMode::Transform | NtscTemporalMode::Hybrid,
        ) => Some(lut::ntsc_3d()),
        _ => None,
    }
}

fn uses_transform(standard: Standard, mode: DecodeMode, ntsc_mode: NtscTemporalMode) -> bool {
    matches!(
        (standard, mode, ntsc_mode),
        (Standard::Pal, DecodeMode::SpatialComb | DecodeMode::TemporalTransform, _)
            | (
                Standard::Ntsc,
                DecodeMode::TemporalTransform,
                NtscTemporalMode::Transform | NtscTemporalMode::Hybrid,
            )
    )
}

fn lut_length(standard: Standard, mode: DecodeMode, ntsc_mode: NtscTemporalMode) -> usize {
    match (standard, mode, ntsc_mode) {
        (Standard::Pal, DecodeMode::SpatialComb, _) => PAL_2D_BINS * LUT_KNOTS,
        (Standard::Pal, DecodeMode::TemporalTransform, _) => PAL_3D_BINS * LUT_KNOTS,
        (
            Standard::Ntsc,
            DecodeMode::TemporalTransform,
            NtscTemporalMode::Transform | NtscTemporalMode::Hybrid,
        ) => NTSC_3D_BINS * LUT_KNOTS,
        _ => 0,
    }
}

fn report(scratch: &DecodeScratch) -> DecodeReport {
    let confidence = if scratch.has_confidence {
        let count = scratch.confidence.len() as f64;
        let sum = scratch
            .confidence
            .iter()
            .map(|&value| f64::from(value))
            .sum::<f64>();
        let mean = sum / count;
        let variance = scratch
            .confidence
            .iter()
            .map(|&value| {
                let delta = f64::from(value) - mean;
                delta * delta
            })
            .sum::<f64>()
            / count;
        (Some(mean), Some(variance.sqrt()))
    } else {
        (None, None)
    };
    let motion_fraction = if scratch.has_motion {
        Some(
            scratch
                .motion
                .iter()
                .map(|&value| f64::from(value))
                .sum::<f64>()
                / scratch.motion.len() as f64,
        )
    } else {
        None
    };
    DecodeReport {
        confidence_mean: confidence.0,
        confidence_std_dev: confidence.1,
        motion_fraction,
    }
}

fn quantize_chroma(source: &[f32], destination: &mut [i32]) {
    debug_assert_eq!(source.len(), destination.len());
    for (destination, &value) in destination.iter_mut().zip(source) {
        *destination = value
            .round()
            .clamp(f32::from(i16::MIN), f32::from(i16::MAX)) as i32;
    }
}

fn bandpass(input: &[u16], output: &mut [f32]) {
    debug_assert_eq!(input.len(), output.len());
    output.fill(0.0);
    if input.len() < 5 {
        return;
    }
    for x in 2..input.len() - 2 {
        output[x] =
            (2.0 * f32::from(input[x]) - f32::from(input[x - 2]) - f32::from(input[x + 2])) * 0.25;
    }
}

fn spatial_comb(current: &[f32], previous: &[f32], next: &[f32], range: f32, output: &mut [i32]) {
    debug_assert_eq!(current.len(), previous.len());
    debug_assert_eq!(current.len(), next.len());
    debug_assert_eq!(current.len(), output.len());
    if current.is_empty() {
        return;
    }
    output[0] = 0;
    for x in 1..current.len() {
        let mut weight_previous = (current[x].abs() - previous[x].abs()).abs()
            + (current[x - 1].abs() - previous[x - 1].abs()).abs()
            - (current[x].abs() + previous[x - 1].abs()) * 0.10;
        let mut weight_next = (current[x].abs() - next[x].abs()).abs()
            + (current[x - 1].abs() - next[x - 1].abs()).abs()
            - (current[x].abs() + next[x - 1].abs()) * 0.10;
        weight_previous = (1.0 - weight_previous / range).clamp(0.0, 1.0);
        weight_next = (1.0 - weight_next / range).clamp(0.0, 1.0);
        let scale = if weight_previous > 0.0 || weight_next > 0.0 {
            if weight_next > 3.0 * weight_previous {
                weight_previous = 0.0;
            } else if weight_previous > 3.0 * weight_next {
                weight_next = 0.0;
            }
            (2.0 / (weight_next + weight_previous)).max(1.0)
        } else if (previous[x].abs() - next[x].abs()).abs() <= ((next[x] + previous[x]) * 0.2).abs()
        {
            weight_previous = 1.0;
            weight_next = 1.0;
            1.0
        } else {
            1.0
        };
        let value = ((current[x] - previous[x]) * weight_previous * scale
            + (current[x] - next[x]) * weight_next * scale)
            * 0.25;
        output[x] = value
            .round()
            .clamp(f32::from(i16::MIN), f32::from(i16::MAX)) as i32;
    }
}

fn fir_row(input: &[i32], taps: &[i32], output: &mut [i32]) {
    debug_assert_eq!(input.len(), output.len());
    let radius = taps.len() / 2;
    for (x, destination) in output.iter_mut().enumerate() {
        let mut accumulator = 0_i64;
        for (tap_index, &tap) in taps.iter().enumerate() {
            let source = x + tap_index;
            if source < radius || source - radius >= input.len() {
                continue;
            }
            accumulator += i64::from(tap) * i64::from(input[source - radius]);
        }
        *destination = ((accumulator + 16_384) >> 15) as i32;
    }
}

fn clamp_u16(value: i32) -> u16 {
    value.clamp(0, i32::from(u16::MAX)) as u16
}

/// Invalid decoder configuration.
#[derive(Clone, Debug, PartialEq)]
pub enum DecodeConfigError {
    /// The public dimensions value is outside one through three.
    UnsupportedDimensions(i64),
    /// The pair-symmetry threshold is outside `(0, 1]`.
    InvalidThreshold(f32),
    /// Luma evidence is negative.
    InvalidEvidence(f32),
    /// Luma evidence is only valid for PAL transform paths.
    UnsupportedEvidence,
    /// A per-bin threshold table needs a transform path.
    ThresholdsNeedTransform,
    /// A per-bin threshold table has the wrong number of entries.
    ThresholdLength {
        /// Required number of threshold values.
        expected: usize,
        /// Supplied number of threshold values.
        actual: usize,
    },
    /// A per-bin threshold was outside `(0, 1]`.
    InvalidThresholdValue,
    /// A trained gain table needs a transform path.
    LutNeedsTransform,
    /// A trained gain table has the wrong size.
    LutLength {
        /// Required number of values.
        expected: usize,
        /// Supplied number of values.
        actual: usize,
    },
    /// A trained gain table contained a value outside `[0, 1]`.
    InvalidLutValue,
}

impl std::fmt::Display for DecodeConfigError {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            Self::UnsupportedDimensions(value) => {
                write!(f, "dimensions must be 1, 2, or 3, got {value}")
            }
            Self::InvalidThreshold(value) => write!(f, "threshold must be in (0, 1], got {value}"),
            Self::InvalidEvidence(value) => write!(f, "evidence must be non-negative, got {value}"),
            Self::UnsupportedEvidence => f.write_str("evidence needs a PAL spectral transform"),
            Self::ThresholdsNeedTransform => {
                f.write_str("per-bin thresholds need a spectral transform")
            }
            Self::ThresholdLength { expected, actual } => {
                write!(f, "per-bin thresholds need {expected} values, got {actual}")
            }
            Self::InvalidThresholdValue => f.write_str("per-bin thresholds must be in (0, 1]"),
            Self::LutNeedsTransform => f.write_str("a trained LUT needs a spectral transform"),
            Self::LutLength { expected, actual } => {
                write!(f, "trained LUT needs {expected} values, got {actual}")
            }
            Self::InvalidLutValue => f.write_str("trained LUT values must be in [0, 1]"),
        }
    }
}

impl std::error::Error for DecodeConfigError {}

/// Invalid decoder input, temporal window, or reusable storage.
#[derive(Clone, Debug, PartialEq)]
pub enum DecodeError {
    /// The planes disagree or do not use the standard's active width.
    PlaneGeometry {
        /// Required raster width.
        expected_width: usize,
        /// Composite source dimensions.
        composite: (usize, usize),
        /// Y output dimensions.
        y: (usize, usize),
        /// U output dimensions.
        u: (usize, usize),
        /// V output dimensions.
        v: (usize, usize),
    },
    /// Active rows extend beyond the broadcast raster.
    RasterPlacement {
        /// First raster row occupied by the source.
        row_offset: usize,
        /// Number of source rows.
        rows: usize,
        /// Raster height for the selected standard.
        raster_height: usize,
    },
    /// The one-frame convenience API cannot satisfy temporal mode.
    TemporalFramesRequired,
    /// A temporal call did not contain the expected source frames and indices.
    TemporalWindow {
        /// Required frame and index count.
        expected: usize,
        /// Supplied source frame count.
        frames: usize,
        /// Supplied frame-index count.
        indices: usize,
    },
    /// A temporal neighbour has different dimensions from the center frame.
    TemporalGeometry {
        /// Center frame dimensions.
        expected: (usize, usize),
        /// Differing neighbour dimensions.
        actual: (usize, usize),
    },
    /// Scratch allocation would overflow addressable storage.
    ScratchSizeOverflow {
        /// Requested width.
        width: usize,
        /// Requested height.
        height: usize,
    },
    /// Reused scratch belongs to a different constant-format clip geometry.
    ScratchGeometry {
        /// Scratch geometry.
        expected: (usize, usize),
        /// Requested decode geometry.
        actual: (usize, usize),
    },
    /// A requested diagnostic was not generated by the selected path.
    MaskUnavailable(MaskKind),
    /// A mask sink's dimensions differ from the decoded raster.
    MaskGeometry {
        /// Decoded raster dimensions.
        expected: (usize, usize),
        /// Mask sink dimensions.
        actual: (usize, usize),
    },
}

impl std::fmt::Display for DecodeError {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            Self::PlaneGeometry {
                expected_width,
                composite,
                y,
                u,
                v,
            } => write!(
                f,
                "decoder needs matching {expected_width}-sample planes; composite={composite:?}, Y={y:?}, U={u:?}, V={v:?}"
            ),
            Self::RasterPlacement {
                row_offset,
                rows,
                raster_height,
            } => write!(
                f,
                "rows {row_offset}..{} exceed the {raster_height}-line raster",
                row_offset + rows
            ),
            Self::TemporalFramesRequired => {
                f.write_str("this decoder needs a temporal frame window")
            }
            Self::TemporalWindow {
                expected,
                frames,
                indices,
            } => write!(
                f,
                "decoder needs {expected} temporal frames and indices, got {frames} frames and {indices} indices"
            ),
            Self::TemporalGeometry { expected, actual } => {
                write!(
                    f,
                    "temporal frame geometry must match {expected:?}, got {actual:?}"
                )
            }
            Self::ScratchSizeOverflow { width, height } => {
                write!(f, "scratch dimensions overflow: {width}x{height}")
            }
            Self::ScratchGeometry { expected, actual } => {
                write!(f, "scratch is {expected:?}, decode requested {actual:?}")
            }
            Self::MaskUnavailable(MaskKind::Motion) => {
                f.write_str("motion mask needs NTSC temporal hybrid mode")
            }
            Self::MaskUnavailable(MaskKind::Confidence) => {
                f.write_str("confidence mask needs a spectral transform")
            }
            Self::MaskGeometry { expected, actual } => {
                write!(f, "mask is {actual:?}, decode is {expected:?}")
            }
        }
    }
}

impl std::error::Error for DecodeError {}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn bandpass_rejects_flat_luma() {
        let input = [20_000_u16; 32];
        let mut output = [1.0_f32; 32];
        bandpass(&input, &mut output);
        assert!(output.iter().all(|&value| value.abs() < f32::EPSILON));
    }

    #[test]
    fn spatial_comb_is_bounded_for_empty_neighbors() {
        let current = [1_000.0_f32; 32];
        let empty = [0.0_f32; 32];
        let mut output = [0_i32; 32];
        spatial_comb(&current, &empty, &empty, 10_000.0, &mut output);
        assert!(output.iter().all(|&value| value.abs() <= 1_000));
    }

    #[test]
    fn temporal_mode_requires_four_neighbours() {
        let decoder = Decoder::new(Standard::Pal, Setup::None, DecodeMode::TemporalTransform);
        assert_eq!(decoder.look(), 4);
    }

    #[test]
    fn pal_lut_has_its_documented_shape() {
        let options =
            DecoderOptions::new(DecodeMode::SpatialComb)
                .with_lut(vec![1.0; PAL_2D_BINS * LUT_KNOTS]);
        assert!(Decoder::with_options(Standard::Pal, Setup::None, options).is_ok());
    }
}
