#ifndef COMP_LUT_TABLES_H
#define COMP_LUT_TABLES_H

/* Trained per-bin soft-gain tables (Wiener gains over the pair-
 * symmetry ratio, 16 knots per bin; the format comp_decode_set_lut
 * takes). Trained by test/calibrate_thresholds.py; regenerated by
 * test/gen_lut_tables.py. */

extern const double comp_lut_builtin_pal_2d[1280];
extern const double comp_lut_builtin_pal_3d[6144];
extern const double comp_lut_builtin_ntsc[12288];

#endif
